name: 'Delete PR comments'
description: 'Delete all comments on a PR'
inputs:
  pr_number:
    description: 'Pull request number'
    required: false
    default: ${{ github.event.pull_request.number }}
  filter:
    description: 'Filter comments by this string'
    required: false
    default: ''
  github_token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
